// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using TransitsTracker.API.Database;

namespace TransitsTracker.API.Migrations
{
    [DbContext(typeof(TransitsTrackerContext))]
    [Migration("20180326213807_addresses")]
    partial class addresses
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TransitsTracker.API.Models.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("City");

                    b.Property<string>("HouseNo");

                    b.Property<string>("Street");

                    b.HasKey("Id");

                    b.ToTable("Address");
                });

            modelBuilder.Entity("TransitsTracker.API.Models.Transit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Date");

                    b.Property<int?>("DestinationAddressId");

                    b.Property<int>("Distance");

                    b.Property<decimal>("Price");

                    b.Property<int?>("SourceAddressId");

                    b.HasKey("Id");

                    b.HasIndex("DestinationAddressId");

                    b.HasIndex("SourceAddressId");

                    b.ToTable("Transits");
                });

            modelBuilder.Entity("TransitsTracker.API.Models.Transit", b =>
                {
                    b.HasOne("TransitsTracker.API.Models.Address", "DestinationAddress")
                        .WithMany()
                        .HasForeignKey("DestinationAddressId");

                    b.HasOne("TransitsTracker.API.Models.Address", "SourceAddress")
                        .WithMany()
                        .HasForeignKey("SourceAddressId");
                });
#pragma warning restore 612, 618
        }
    }
}
