// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using TransitsTracker.API.Database;

namespace TransitsTracker.API.Migrations
{
    [DbContext(typeof(TransitsTrackerContext))]
    partial class TransitsTrackerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TransitsTracker.API.Models.Transit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Date");

                    b.Property<string>("DestinationAddress");

                    b.Property<int>("Distance");

                    b.Property<decimal>("Price");

                    b.Property<string>("SourceAddress");

                    b.HasKey("Id");

                    b.ToTable("Transits");
                });
#pragma warning restore 612, 618
        }
    }
}
